### ISSUE TITLE
Implementation details about "Comparison on Different Scales"

### ISSUE THREAD

**Issue by charon517-517** [Reagan1311/LOCATE#7]
I'm curious about how to evaluate LOCATE to get the results from Table 2. in supplementary material. Like how to calculate 'the ratio of the mask' given a GT_mask? 
For example, can I set a fixed threshold value to get a binary mask from GT_mask which served as the affordance region, use 'mask.sum() / (GT_mask_h * GT_mask_w)' as the ratio?
<img width="935" alt="截屏2024-10-24 12 17 46" src="https://github.com/user-attachments/assets/f0c41a79-3892-4d2c-ab08-017b75af2ea9">

**Comment by Reagan1311** [comment]
Hi, if I remember correctly, the computation should be based on the original mask rather than applying a threshold. The values of the original mask range from 0 to 255. First, divide by 255, then compute `mask.sum() / (GT_mask_h * GT_mask_w)` to classify based on the following criteria: Large (ratio > 0.1), Medium (0.03 ≤ ratio ≤ 0.1), and Small (ratio < 0.03).

**Comment by charon517-517** [comment]
> Hi, if I remember correctly, the computation should be based on the original mask rather than applying a threshold. The values of the original mask range from 0 to 255. First, divide by 255, then compute `mask.sum() / (GT_mask_h * GT_mask_w)` to classify based on the following criteria: Large (ratio > 0.1), Medium (0.03 ≤ ratio ≤ 0.1), and Small (ratio < 0.03).

Thanks for your reply! I understand how to reproduce the results now. Thanks again for your excellent work!
